name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      uses: cypress-io/github-action@v4
      with:
        command:  npm run cy:e2e

    - name: Uploading artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-execution-report
        path: /mochawesome-report
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-html-report
