name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cy:e2e

    - name: Archive JUnit results
      if: always() # Ensure this step runs even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: cypress/results/junit/result.xml

    - name: Archive Mochawesome report
      if: always() # Ensure this step runs even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        path: cypress/results/mochawesome/mochawesome.html # Assuming the HTML report is generated in this location

    - name: Archive Cypress results
      if: always() # Ensure this step runs even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: cypress-test-results
        path: cypress/results
